//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngeSoftVirtual.ServiceWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.ingesoft.pucp.edu.pe/", ConfigurationName="ServiceWS.ServiceWS")]
    public interface ServiceWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ingesoft.pucp.edu.pe/ServiceWS/InsertarCursoRequest", ReplyAction="http://services.ingesoft.pucp.edu.pe/ServiceWS/InsertarCursoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        IngeSoftVirtual.ServiceWS.InsertarCursoResponse InsertarCurso(IngeSoftVirtual.ServiceWS.InsertarCursoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ingesoft.pucp.edu.pe/ServiceWS/InsertarCursoRequest", ReplyAction="http://services.ingesoft.pucp.edu.pe/ServiceWS/InsertarCursoResponse")]
        System.Threading.Tasks.Task<IngeSoftVirtual.ServiceWS.InsertarCursoResponse> InsertarCursoAsync(IngeSoftVirtual.ServiceWS.InsertarCursoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ingesoft.pucp.edu.pe/ServiceWS/helloRequest", ReplyAction="http://services.ingesoft.pucp.edu.pe/ServiceWS/helloResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        IngeSoftVirtual.ServiceWS.helloResponse hello(IngeSoftVirtual.ServiceWS.helloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ingesoft.pucp.edu.pe/ServiceWS/helloRequest", ReplyAction="http://services.ingesoft.pucp.edu.pe/ServiceWS/helloResponse")]
        System.Threading.Tasks.Task<IngeSoftVirtual.ServiceWS.helloResponse> helloAsync(IngeSoftVirtual.ServiceWS.helloRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ingesoft.pucp.edu.pe/ServiceWS/ListarCursoPorNombreRequest", ReplyAction="http://services.ingesoft.pucp.edu.pe/ServiceWS/ListarCursoPorNombreResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        IngeSoftVirtual.ServiceWS.ListarCursoPorNombreResponse ListarCursoPorNombre(IngeSoftVirtual.ServiceWS.ListarCursoPorNombreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ingesoft.pucp.edu.pe/ServiceWS/ListarCursoPorNombreRequest", ReplyAction="http://services.ingesoft.pucp.edu.pe/ServiceWS/ListarCursoPorNombreResponse")]
        System.Threading.Tasks.Task<IngeSoftVirtual.ServiceWS.ListarCursoPorNombreResponse> ListarCursoPorNombreAsync(IngeSoftVirtual.ServiceWS.ListarCursoPorNombreRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ingesoft.pucp.edu.pe/ServiceWS/ListarTodasEspecialidadesRequest", ReplyAction="http://services.ingesoft.pucp.edu.pe/ServiceWS/ListarTodasEspecialidadesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        IngeSoftVirtual.ServiceWS.ListarTodasEspecialidadesResponse ListarTodasEspecialidades(IngeSoftVirtual.ServiceWS.ListarTodasEspecialidadesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ingesoft.pucp.edu.pe/ServiceWS/ListarTodasEspecialidadesRequest", ReplyAction="http://services.ingesoft.pucp.edu.pe/ServiceWS/ListarTodasEspecialidadesResponse")]
        System.Threading.Tasks.Task<IngeSoftVirtual.ServiceWS.ListarTodasEspecialidadesResponse> ListarTodasEspecialidadesAsync(IngeSoftVirtual.ServiceWS.ListarTodasEspecialidadesRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ingesoft.pucp.edu.pe/")]
    public partial class curso : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private string claveField;
        
        private int creditosField;
        
        private especialidad especialidadField;
        
        private System.DateTime fechaFinField;
        
        private bool fechaFinFieldSpecified;
        
        private System.DateTime fechaInicioField;
        
        private bool fechaInicioFieldSpecified;
        
        private int idCursoField;
        
        private string nombreField;
        
        private double precioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string clave {
            get {
                return this.claveField;
            }
            set {
                this.claveField = value;
                this.RaisePropertyChanged("clave");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int creditos {
            get {
                return this.creditosField;
            }
            set {
                this.creditosField = value;
                this.RaisePropertyChanged("creditos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public especialidad especialidad {
            get {
                return this.especialidadField;
            }
            set {
                this.especialidadField = value;
                this.RaisePropertyChanged("especialidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime fechaFin {
            get {
                return this.fechaFinField;
            }
            set {
                this.fechaFinField = value;
                this.RaisePropertyChanged("fechaFin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaFinSpecified {
            get {
                return this.fechaFinFieldSpecified;
            }
            set {
                this.fechaFinFieldSpecified = value;
                this.RaisePropertyChanged("fechaFinSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime fechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
                this.RaisePropertyChanged("fechaInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaInicioSpecified {
            get {
                return this.fechaInicioFieldSpecified;
            }
            set {
                this.fechaInicioFieldSpecified = value;
                this.RaisePropertyChanged("fechaInicioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int idCurso {
            get {
                return this.idCursoField;
            }
            set {
                this.idCursoField = value;
                this.RaisePropertyChanged("idCurso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public double precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
                this.RaisePropertyChanged("precio");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ingesoft.pucp.edu.pe/")]
    public partial class especialidad : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private int idEspecialidadField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idEspecialidad {
            get {
                return this.idEspecialidadField;
            }
            set {
                this.idEspecialidadField = value;
                this.RaisePropertyChanged("idEspecialidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertarCurso", WrapperNamespace="http://services.ingesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class InsertarCursoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ingesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IngeSoftVirtual.ServiceWS.curso arg0;
        
        public InsertarCursoRequest() {
        }
        
        public InsertarCursoRequest(IngeSoftVirtual.ServiceWS.curso arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertarCursoResponse", WrapperNamespace="http://services.ingesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class InsertarCursoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ingesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public InsertarCursoResponse() {
        }
        
        public InsertarCursoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="hello", WrapperNamespace="http://services.ingesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class helloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ingesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name;
        
        public helloRequest() {
        }
        
        public helloRequest(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="helloResponse", WrapperNamespace="http://services.ingesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ingesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public helloResponse() {
        }
        
        public helloResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarCursoPorNombre", WrapperNamespace="http://services.ingesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class ListarCursoPorNombreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ingesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public ListarCursoPorNombreRequest() {
        }
        
        public ListarCursoPorNombreRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarCursoPorNombreResponse", WrapperNamespace="http://services.ingesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class ListarCursoPorNombreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ingesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IngeSoftVirtual.ServiceWS.curso[] @return;
        
        public ListarCursoPorNombreResponse() {
        }
        
        public ListarCursoPorNombreResponse(IngeSoftVirtual.ServiceWS.curso[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarTodasEspecialidades", WrapperNamespace="http://services.ingesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class ListarTodasEspecialidadesRequest {
        
        public ListarTodasEspecialidadesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarTodasEspecialidadesResponse", WrapperNamespace="http://services.ingesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class ListarTodasEspecialidadesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.ingesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IngeSoftVirtual.ServiceWS.especialidad[] @return;
        
        public ListarTodasEspecialidadesResponse() {
        }
        
        public ListarTodasEspecialidadesResponse(IngeSoftVirtual.ServiceWS.especialidad[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceWSChannel : IngeSoftVirtual.ServiceWS.ServiceWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceWSClient : System.ServiceModel.ClientBase<IngeSoftVirtual.ServiceWS.ServiceWS>, IngeSoftVirtual.ServiceWS.ServiceWS {
        
        public ServiceWSClient() {
        }
        
        public ServiceWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IngeSoftVirtual.ServiceWS.InsertarCursoResponse IngeSoftVirtual.ServiceWS.ServiceWS.InsertarCurso(IngeSoftVirtual.ServiceWS.InsertarCursoRequest request) {
            return base.Channel.InsertarCurso(request);
        }
        
        public int InsertarCurso(IngeSoftVirtual.ServiceWS.curso arg0) {
            IngeSoftVirtual.ServiceWS.InsertarCursoRequest inValue = new IngeSoftVirtual.ServiceWS.InsertarCursoRequest();
            inValue.arg0 = arg0;
            IngeSoftVirtual.ServiceWS.InsertarCursoResponse retVal = ((IngeSoftVirtual.ServiceWS.ServiceWS)(this)).InsertarCurso(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IngeSoftVirtual.ServiceWS.InsertarCursoResponse> IngeSoftVirtual.ServiceWS.ServiceWS.InsertarCursoAsync(IngeSoftVirtual.ServiceWS.InsertarCursoRequest request) {
            return base.Channel.InsertarCursoAsync(request);
        }
        
        public System.Threading.Tasks.Task<IngeSoftVirtual.ServiceWS.InsertarCursoResponse> InsertarCursoAsync(IngeSoftVirtual.ServiceWS.curso arg0) {
            IngeSoftVirtual.ServiceWS.InsertarCursoRequest inValue = new IngeSoftVirtual.ServiceWS.InsertarCursoRequest();
            inValue.arg0 = arg0;
            return ((IngeSoftVirtual.ServiceWS.ServiceWS)(this)).InsertarCursoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IngeSoftVirtual.ServiceWS.helloResponse IngeSoftVirtual.ServiceWS.ServiceWS.hello(IngeSoftVirtual.ServiceWS.helloRequest request) {
            return base.Channel.hello(request);
        }
        
        public string hello(string name) {
            IngeSoftVirtual.ServiceWS.helloRequest inValue = new IngeSoftVirtual.ServiceWS.helloRequest();
            inValue.name = name;
            IngeSoftVirtual.ServiceWS.helloResponse retVal = ((IngeSoftVirtual.ServiceWS.ServiceWS)(this)).hello(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IngeSoftVirtual.ServiceWS.helloResponse> IngeSoftVirtual.ServiceWS.ServiceWS.helloAsync(IngeSoftVirtual.ServiceWS.helloRequest request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<IngeSoftVirtual.ServiceWS.helloResponse> helloAsync(string name) {
            IngeSoftVirtual.ServiceWS.helloRequest inValue = new IngeSoftVirtual.ServiceWS.helloRequest();
            inValue.name = name;
            return ((IngeSoftVirtual.ServiceWS.ServiceWS)(this)).helloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IngeSoftVirtual.ServiceWS.ListarCursoPorNombreResponse IngeSoftVirtual.ServiceWS.ServiceWS.ListarCursoPorNombre(IngeSoftVirtual.ServiceWS.ListarCursoPorNombreRequest request) {
            return base.Channel.ListarCursoPorNombre(request);
        }
        
        public IngeSoftVirtual.ServiceWS.curso[] ListarCursoPorNombre(string arg0) {
            IngeSoftVirtual.ServiceWS.ListarCursoPorNombreRequest inValue = new IngeSoftVirtual.ServiceWS.ListarCursoPorNombreRequest();
            inValue.arg0 = arg0;
            IngeSoftVirtual.ServiceWS.ListarCursoPorNombreResponse retVal = ((IngeSoftVirtual.ServiceWS.ServiceWS)(this)).ListarCursoPorNombre(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IngeSoftVirtual.ServiceWS.ListarCursoPorNombreResponse> IngeSoftVirtual.ServiceWS.ServiceWS.ListarCursoPorNombreAsync(IngeSoftVirtual.ServiceWS.ListarCursoPorNombreRequest request) {
            return base.Channel.ListarCursoPorNombreAsync(request);
        }
        
        public System.Threading.Tasks.Task<IngeSoftVirtual.ServiceWS.ListarCursoPorNombreResponse> ListarCursoPorNombreAsync(string arg0) {
            IngeSoftVirtual.ServiceWS.ListarCursoPorNombreRequest inValue = new IngeSoftVirtual.ServiceWS.ListarCursoPorNombreRequest();
            inValue.arg0 = arg0;
            return ((IngeSoftVirtual.ServiceWS.ServiceWS)(this)).ListarCursoPorNombreAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IngeSoftVirtual.ServiceWS.ListarTodasEspecialidadesResponse IngeSoftVirtual.ServiceWS.ServiceWS.ListarTodasEspecialidades(IngeSoftVirtual.ServiceWS.ListarTodasEspecialidadesRequest request) {
            return base.Channel.ListarTodasEspecialidades(request);
        }
        
        public IngeSoftVirtual.ServiceWS.especialidad[] ListarTodasEspecialidades() {
            IngeSoftVirtual.ServiceWS.ListarTodasEspecialidadesRequest inValue = new IngeSoftVirtual.ServiceWS.ListarTodasEspecialidadesRequest();
            IngeSoftVirtual.ServiceWS.ListarTodasEspecialidadesResponse retVal = ((IngeSoftVirtual.ServiceWS.ServiceWS)(this)).ListarTodasEspecialidades(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IngeSoftVirtual.ServiceWS.ListarTodasEspecialidadesResponse> IngeSoftVirtual.ServiceWS.ServiceWS.ListarTodasEspecialidadesAsync(IngeSoftVirtual.ServiceWS.ListarTodasEspecialidadesRequest request) {
            return base.Channel.ListarTodasEspecialidadesAsync(request);
        }
        
        public System.Threading.Tasks.Task<IngeSoftVirtual.ServiceWS.ListarTodasEspecialidadesResponse> ListarTodasEspecialidadesAsync() {
            IngeSoftVirtual.ServiceWS.ListarTodasEspecialidadesRequest inValue = new IngeSoftVirtual.ServiceWS.ListarTodasEspecialidadesRequest();
            return ((IngeSoftVirtual.ServiceWS.ServiceWS)(this)).ListarTodasEspecialidadesAsync(inValue);
        }
    }
}
