//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngeSoftVirtual.ServicioWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.ingesoft.pucp.edu.pe/", ConfigurationName="ServicioWS.WebService2")]
    public interface WebService2 {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento name del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ingesoft.pucp.edu.pe/WebService2/helloRequest", ReplyAction="http://services.ingesoft.pucp.edu.pe/WebService2/helloResponse")]
        IngeSoftVirtual.ServicioWS.helloResponse hello(IngeSoftVirtual.ServicioWS.helloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ingesoft.pucp.edu.pe/WebService2/helloRequest", ReplyAction="http://services.ingesoft.pucp.edu.pe/WebService2/helloResponse")]
        System.Threading.Tasks.Task<IngeSoftVirtual.ServicioWS.helloResponse> helloAsync(IngeSoftVirtual.ServicioWS.helloRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="hello", Namespace="http://services.ingesoft.pucp.edu.pe/", Order=0)]
        public IngeSoftVirtual.ServicioWS.helloRequestBody Body;
        
        public helloRequest() {
        }
        
        public helloRequest(IngeSoftVirtual.ServicioWS.helloRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class helloRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public helloRequestBody() {
        }
        
        public helloRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="helloResponse", Namespace="http://services.ingesoft.pucp.edu.pe/", Order=0)]
        public IngeSoftVirtual.ServicioWS.helloResponseBody Body;
        
        public helloResponse() {
        }
        
        public helloResponse(IngeSoftVirtual.ServicioWS.helloResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class helloResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public helloResponseBody() {
        }
        
        public helloResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService2Channel : IngeSoftVirtual.ServicioWS.WebService2, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService2Client : System.ServiceModel.ClientBase<IngeSoftVirtual.ServicioWS.WebService2>, IngeSoftVirtual.ServicioWS.WebService2 {
        
        public WebService2Client() {
        }
        
        public WebService2Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService2Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IngeSoftVirtual.ServicioWS.helloResponse IngeSoftVirtual.ServicioWS.WebService2.hello(IngeSoftVirtual.ServicioWS.helloRequest request) {
            return base.Channel.hello(request);
        }
        
        public string hello(string name) {
            IngeSoftVirtual.ServicioWS.helloRequest inValue = new IngeSoftVirtual.ServicioWS.helloRequest();
            inValue.Body = new IngeSoftVirtual.ServicioWS.helloRequestBody();
            inValue.Body.name = name;
            IngeSoftVirtual.ServicioWS.helloResponse retVal = ((IngeSoftVirtual.ServicioWS.WebService2)(this)).hello(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IngeSoftVirtual.ServicioWS.helloResponse> IngeSoftVirtual.ServicioWS.WebService2.helloAsync(IngeSoftVirtual.ServicioWS.helloRequest request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<IngeSoftVirtual.ServicioWS.helloResponse> helloAsync(string name) {
            IngeSoftVirtual.ServicioWS.helloRequest inValue = new IngeSoftVirtual.ServicioWS.helloRequest();
            inValue.Body = new IngeSoftVirtual.ServicioWS.helloRequestBody();
            inValue.Body.name = name;
            return ((IngeSoftVirtual.ServicioWS.WebService2)(this)).helloAsync(inValue);
        }
    }
}
